import { useState } from 'react';
import { ArrowUpRight, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Header,Footer,FloatingControls } from './chrome';
import { ProjectCard } from './project-card';
import { getProject, projects } from '@/lib/portfolio';
export function ProjectDetail({slug}:{slug:string}){
 const [zoom,setZoom]=useState<string|null>(null);const project=getProject(slug);
 if(!project)return null;
 return <div className="detail-page light-sections"><Header light/><FloatingControls/><main className="detail-main"><div className="detail-intro"><div><span className="eyebrow">PROJECT {String(projects.indexOf(project)+1).padStart(2,'0')}</span><h1>{project.name}</h1><p>{project.description}</p></div><div className="detail-role"><small>Category</small><p>{project.category}</p></div><div className="detail-stack"><small>Stack</small>{project.stack.map(item=><p key={item}>{item}</p>)}</div></div><img className="detail-hero" src={project.image} alt={`${project.name} interface`}/><div className="detail-copy"><section><h2>OVERVIEW</h2><p>{project.overview}</p><Button asChild variant="outline" className="contact-button"><a href={project.url} target="_blank" rel="noreferrer">Visit live project <ArrowUpRight size={16}/></a></Button></section></div><section className="screens-section"><h2>PROJECT PREVIEW</h2><div className="screens-grid"><Button variant="ghost" className="screen-button" onClick={()=>setZoom(project.image)} aria-label={`Enlarge ${project.name} preview`}><img src={project.image} alt={`${project.name} project preview`} loading="lazy"/></Button></div></section><section className="more-work"><h2>MORE WORK</h2><div className="project-grid">{projects.filter(p=>p.slug!==slug).slice(0,2).map(p=><ProjectCard project={p} index={projects.indexOf(p)} key={p.slug}/>)}</div></section></main><Footer/>{zoom&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label="Project screenshot" onClick={()=>setZoom(null)}><Button variant="ghost" size="icon" aria-label="Close screenshot" onClick={()=>setZoom(null)}><X/></Button><img src={zoom} alt={`${project.name} screenshot`} onClick={event=>event.stopPropagation()}/></div>}</div>
}
